[tools]
luau-lsp = "johnnymorganz/luau-lsp@1.53.3"
lunar = "corecii/lunar@0.1.0"
lune = "lune-org/lune@0.10.2"
rojo = "rojo-rbx/rojo@7.5.1"
selene = "howmanysmall/selene@0.29.0"      #"kampfkarren/selene@0.30.0" # when updated
