[package]
name = "howmanysmall/profileservice-plus"
version = "0.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Janitor = "howmanysmall/janitor@1.15.7"
Signal = "howmanysmall/better-signal@1.0.0"
Promise = "evaera/promise@4.0.0-rc.2"
